resources:
- repo: self
  clean: true

pool:
  vmImage: windows-latest
  
trigger:
  batch: true
  branches:
    include: 
    - master 

variables:
  ComponentDetection.Timeout: 1200

steps:
  - task: ComponentGovernanceComponentDetection@0
